### ISSUE TITLE
Any plans for localisation?

### ISSUE THREAD

**Issue by itsam** [freearhey/dayjs-twitter#1]
Hello and thank you for your plugin.
Do you have any plans to localise your plugin?
Right now if you do the following 
```
    const ago = dayjs(myDate).locale('el').twitter();
```
works partially (e.g. only month is translated but not the "h", "m", "now", etc...
Thank  you in advance

**Comment by freearhey** [comment]
Honestly, I didn't think about it before 🤔But I think I can try to add some minimal support for localization in the next update. Thank you for the idea!

**Comment by freearhey** [comment]
Done! I have just published the `v0.2.0` version which supports different locales. 

Currently there are only 3 languages in the list (English, Spanish and Russian). But you can easily add any other language. To do this, you just need to create a template file in the `src/locale` folder. Here's an example:

```js
export default {
  now: 'Now',
  seconds: '%ds',
  minutes: '%dm',
  hours: '%dh',
  days: 'MMM D',
  years: 'MMM D, YYYY'
}
```

**Comment by itsam** [comment]
Thank you @freearhey but I am not sure I understand how to make it work... I use the following
```
import dayjs from 'dayjs';
import dayjsTwitter from 'dayjs-twitter';
import 'dayjs/locale/es';
dayjs.locale('es');
dayjs.extend(dayjsTwitter);

const ago = dayjs(this.props.date)
      .locale('es')
      .twitter();
```
but no luck...
Any ideas?

**Comment by itsam** [comment]
I am using react native and the error deals with line 14
```
const locale = require(`./locale/${locName}`).default
```
about
```
Error: Dynamic require defined at line 14; not supported by Metro
```
So maybe it is smt on RN side rather than your script

**Comment by itsam** [comment]
Indeed the problem is on the RN side... so the following works but it's an overkill 
```
  //const locale = require(`./locale/${locName}`).default
  let locale = null;
  switch (locName) {
    case 'es': locale = require('./locale/es').default;break;
    case 'ru': locale = require('./locale/ru').default;break;
    default: locale = require('./locale/en').default;
  }
```

**Comment by itsam** [comment]
Let me known if you want me to make a PR with the above (and also include el and fr) or you 're preferring to keep it "web-oriented" as is.

**Comment by freearhey** [comment]
@itsam I've just made some changes to the build, please try upgrade to `v0.2.1` and check again.

This code should work:

```js
import dayjs from 'dayjs'
import dayjsTwitter from 'dayjs-twitter'
import 'dayjs/locale/es'

dayjs.extend(dayjsTwitter)
dayjs.locale('es')

const ago = dayjs().twitter() // => Ahora
```

**Comment by itsam** [comment]
Your code is perfect. The actual problem is on React Native side which does not (still) allow dynamic "require".

**Comment by freearhey** [comment]
Done.
